# Generated by Django 2.0.2 on 2018-02-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_items', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_change_date', models.DateTimeField(auto_now=True)),
                ('owner', models.SmallIntegerField(default=0)),
                ('lifecycle', models.CharField(choices=[('OPEN', 'open'), ('CLOSED', 'closed')], default='open', max_length=10)),
                ('table_number', models.IntegerField(default=0)),
            ],
        ),
    ]
