# Generated by Django 2.0.2 on 2018-02-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20180223_0734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterModelOptions(
            name='itemtemplate',
            options={'ordering': ['print_order']},
        ),
    ]
