# Generated by Django 2.0.2 on 2018-02-23 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20180223_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemtemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pos.ItemTemplate')),
                ('option', models.CharField(max_length=3)),
            ],
            bases=('pos.itemtemplate',),
        ),
    ]
