# Generated by Django 2.0.2 on 2018-02-23 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shopping_basket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos.ShoppingBasket'),
            preserve_default=False,
        ),
    ]
