# Generated by Django 2.0.2 on 2018-02-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_subitemtemplate_item_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subitemtemplate',
            name='item_template',
        ),
    ]
