# Generated by Django 2.0.2 on 2018-02-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_remove_subitemtemplate_item_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='subitemtemplate',
            name='item_template',
            field=models.ManyToManyField(to='pos.ItemTemplate'),
        ),
    ]
