# Generated by Django 2.0.2 on 2018-02-23 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_subitemtemplate_item_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pos.ItemTemplate'),
        ),
    ]
