# Generated by Django 2.0.2 on 2018-02-23 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_subitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='subitem',
            name='shopping_basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.ShoppingBasket'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.Item'),
        ),
    ]
